#!/bin/bash

for BIN in pkg-config curl cmake xxd
do
    if ! type $BIN >/dev/null; then
        echo "Please, install $BIN." >&2
        exit 1
    fi
done

# https://stackoverflow.com/a/4025065
vercomp ()
{
    if [[ $1 == $2 ]]
    then
        return 0
    fi
    local IFS=.
    local i ver1=($1) ver2=($2)
    # fill empty fields in ver1 with zeros
    for ((i=${#ver1[@]}; i<${#ver2[@]}; i++))
    do
        ver1[i]=0
    done
    for ((i=0; i<${#ver1[@]}; i++))
    do
        if [[ -z ${ver2[i]} ]]
        then
            # fill empty fields in ver2 with zeros
            ver2[i]=0
        fi
        if ((10#${ver1[i]} > 10#${ver2[i]}))
        then
            return 1
        fi
        if ((10#${ver1[i]} < 10#${ver2[i]}))
        then
            return 2
        fi
    done
    return 0
}

(
    # Change dir to script's
    {
        src="${BASH_SOURCE[0]}"
        while [[ -L ${src} ]]; do
            # shellcheck disable=SC1117
            src=$(find "${src}" -type l -ls | sed -n 's/^.* -> \(.*\)/\1/p')
        done
        dir=$(cd -P "$(dirname "${src}")" && pwd)
        cd $dir || exit 1
    }

    if ! pkg-config --exists --print-errors sqlite3; then
        ./install-sqlite3
    else
        VERSION=$(pkg-config --modversion sqlite3)
        vercomp $VERSION 3.35.0
        [[ $? == 2 ]] && ./install-sqlite3
    fi

    if ! pkg-config --exists --print-errors libxxhash; then
        ./install-xxhash
    fi
)

bash -c "$(curl -fsSL https://git.io/Jz7Oa)" -s horta/hope || exit 1
