#!/bin/bash

set -e

(
    FILE=sqlite-autoconf-3360000.tar.gz
    DIR=sqlite-autoconf-3360000
    URL=https://www.sqlite.org/2021/$FILE

    cd ~/
    curl $URL -o $FILE -s -L
    tar xzf $FILE
    cd $DIR
    if type sudo >/dev/null 2>&1; then SUDO="sudo"; else SUDO=""; fi
    ./configure && make && $SUDO make install
    cd ..
    /bin/rm -f $FILE
    /bin/rm -rf $DIR
)
