#!/bin/bash

if ! type pkg-config >/dev/null; then
    echo "Please, install pkg-config." >&2
    exit 1
fi

if ! pkg-config --exists --print-errors libxxhash; then
    echo "Please, install xxhash." >&2
    exit 1
fi

(
    # Change dir to script's
    {
        src="${BASH_SOURCE[0]}"
        while [[ -L ${src} ]]; do
            # shellcheck disable=SC1117
            src=$(find "${src}" -type l -ls | sed -n 's/^.* -> \(.*\)/\1/p')
        done
        dir=$(cd -P "$(dirname "${src}")" && pwd)
        cd $dir || exit 1
    }

    if ! pkg-config --exists --print-errors sqlite3; then
        ./install-sqlite3
    fi
)

bash -c "$(curl -fsSL https://git.io/Jz7Oa)" -s horta/hope || exit 1
bash -c "$(curl -fsSL https://git.io/Jz7Oa)" -s EBI-Metagenomics/log || exit 1
