#!/bin/bash

set -e

(
    VERSION=0.8.1
    FILE=v$VERSION.tar.gz
    DIR=xxHash-$VERSION
    URL=https://github.com/Cyan4973/xxHash/archive/refs/tags/$FILE

    cd ~/
    curl $URL -o $FILE -s -L
    tar xzf $FILE
    cd $DIR
    if type sudo >/dev/null 2>&1; then SUDO="sudo"; else SUDO=""; fi
    make && $SUDO make install
    cd ..
    /bin/rm -f $FILE
    /bin/rm -rf $DIR
)
