#ifndef DCP_SCHED_LIMITS_H
#define DCP_SCHED_LIMITS_H

enum sched_limits
{
    SCHED_ABC_NAME_SIZE = 16,
    SCHED_JOB_ERROR_SIZE = 256,
    SCHED_JOB_STATE_SIZE = 5,
    SCHED_NUM_SEQS_PER_JOB = 64,
    SCHED_PATH_SIZE = 4096,
    SCHED_PROFILE_NAME_SIZE = 256,
    SCHED_PROFILE_TYPEID_SIZE = 16,
    SCHED_SEQ_NAME_SIZE = 256,
    SCHED_SEQ_SIZE = (1024 * 1024),
    SCHED_VERSION_SIZE = 16,
};

#endif
