#ifndef DCP_SCHED_LIMITS_H
#define DCP_SCHED_LIMITS_H

enum dcp_sched_limits
{
    DCP_PATH_SIZE = 4096,
    DCP_SEQ_NAME_SIZE = 256,
    DCP_ABC_NAME_SIZE = 16,
    DCP_SEQ_SIZE = (1024 * 1024),
    DCP_NUM_SEQS_PER_JOB = 64,
    DCP_PROFILE_TYPEID_SIZE = 16,
    DCP_PROF_NAME_SIZE = 256,
    DCP_VERSION_SIZE = 16,
    DCP_MAX_NPROFILES = (1 << 20),
    DCP_PROFILE_NAME_SIZE = 64,
    DCP_PROFILE_ACC_SIZE = 32,
    SCHED_JOB_STATE_SIZE = 5,
    SCHED_JOB_ERROR_SIZE = 256,
};

#endif
