#!/bin/bash

function show_usage {
    echo "Usage: embed-file RESOURCE_FILE SYMBOL OUTPUT_FILE"
    echo "  Outputs C file from the contents of RESOURCE_FILE"
    echo "  into OUTPUT_FILE."
}

if [ $# -ne 3 ]; then
    show_usage
    exit 1
fi

resource_file=$1
symbol=$2
output_file=$3

{
    echo "#include <stdlib.h>"
    echo
    echo "unsigned char const ${symbol}[] = {"

    # Mimics `xxd -i` command.
    i=0
    while LANG=C IFS= read -r -d '' -n 1 byte; do
        printf -v decimal %d "'""$byte"

        if [ "$((i % 12))" == "0" ]; then
            printf "    "
        else
            printf ", "
        fi

        printf "0x%02x" "$decimal"
        i=$((i + 1))
        if [ "$((i % 12))" == "0" ]; then
            echo ","
        fi
    done <"$resource_file"

    echo ", 0x00};"
    echo
    echo "size_t const ${symbol}_size = sizeof(${symbol});"
} >"$output_file"
