#!/bin/bash

if ! type xxd; then
    echo "Please, install xxd." >&2
    exit 1
fi

function show_usage
{
    echo "Usage: embed-file RESOURCE_FILE SYMBOL OUTPUT_FILE"
    echo "  Outputs C file from the contents of RESOURCE_FILE"
    echo "  into OUTPUT_FILE."
}

if [ $# -ne 3 ]; then
    show_usage
    exit 1
fi

resource_file=$1
symbol=$2
output_file=$3

echo "#include <stdlib.h>" >$output_file
echo "" >>$output_file
echo "unsigned char const ${symbol}[] = {" >>$output_file
tmp=$(cat $resource_file <(printf '\0') | xxd -i | sed 's/^  /    /')
echo "$tmp};" >>$output_file
echo "" >>$output_file
echo "size_t const ${symbol}_size = sizeof(${symbol});" >>$output_file
