#ifndef SCHED_LIMITS_H
#define SCHED_LIMITS_H

enum sched_limits
{
    ABC_NAME_SIZE = 16,
    BITS_PER_PROFILE_TYPEID = 16,
    FILENAME_SIZE = 128,
    JOB_ERROR_SIZE = 256,
    JOB_STATE_SIZE = 5,
    MATCH_SIZE = 5 * (1024 * 1024),
    MAX_NPROFILES = (1 << 20),
    MAX_NUM_THREADS = 64,
    NUM_PARTITIONS = 64,
    NUM_SEQS_PER_JOB = 64,
    PATH_SIZE = 4096,
    PROFILE_ACC_SIZE = 32,
    PROFILE_NAME_SIZE = 64,
    PROFILE_TYPEID_SIZE = 16,
    PROF_NAME_SIZE = 256,
    PROTEIN_MODEL_CORE_SIZE_MAX = 2048,
    SEQ_NAME_SIZE = 256,
    SEQ_SIZE = (1024 * 1024),
    VERSION_SIZE = 16,
    ERROR_SIZE = 256,
};

#endif
